#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=24:00:00
#SBATCH --mem=64000M
#SBATCH --output=out_job/train_spanish_stereotype_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/MultiLingual_Stereotypes
source activate multilingual
# Run your code
srun python train_spanish_stereotype.py --output_directory ./xlm-roberta-finetuned/spanish_fine_tuning --epochs 5